image:
  - Visual Studio 2019
  - Ubuntu

build_script:
- ps: >-
    dotnet build src --configuration Debug

    dotnet test src --configuration Debug --no-build --no-restore
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off
artifacts:
- path: nugets\*.nupkg
